package com.fourthrock.invade.game.scene;

import com.fourthrock.invade.draw.CanvasRenderer;
import com.fourthrock.invade.draw.Screen2D;

/**
 * Represents a logical state or "scene" in the GameState
 * @author Joseph
 *
 */
public interface Scene {

	/**
	 * Update the state by dt (comes in milliseconds).
	 * 
	 * Return the next Scene for the GameState to run.
	 * If supposed to remain in the same Scene, return <code>this</code>.
	 * 
	 * @param dt, the time in milliseconds since the last step started
	 */
	public Scene step(final long dt);

	/**
	 * The user made a pan motion. Take the coordinates
	 * of the beginning of the motion and the end, and
	 * figure it out from there.
	 */
	public void handlePan(final Screen2D start, final Screen2D end);

	/**
	 * The user made a quick, single tap. Take the tap's
	 * location in screen space and determine what to do.
	 * @param screenCoords
	 * @param x, the x coordinate
	 * @param y, the y coordinate
	 */
	public void handleTap(final Screen2D screenCoords);

	/**
	 * The user made a scaling gesture (pinching, zooming).
	 * Take the scaling factor and determine what to do.
	 * 
	 * @param scaleFactor, the scaling amount generated by the gesture
	 */
	public void handleScaling(final float scaleFactor);
	
	/**
	 * The user made a fling motion.
	 * Take the velocity of the fling (in pixels per second)
	 * and the last touched point on the screen
	 * to determine what to do.
	 * 
	 * @param start, the last touched point on the screen
	 * @param velocity, the velocity in screen coordinates
	 */
	public void handleFling(final Screen2D start, Screen2D velocity);
	
	/**
	 * Return the {x,y,z} coordinates for the current camera
	 */
	public float[] getEye();

	/**
	 * Return the zoom factor for the current camera.
	 */
	public float getZoom();

	/**
	 * With the GameRenderer, draw out all necessary
	 * components.
	 * 
	 * @param renderer, the GameRenderer object with which
	 * 			to do thy bidding.
	 */
	public void render(final CanvasRenderer renderer);


}
